
# 操作冷却 (单位: 秒)
cd_knock: 420
cd_random: 500
cd_money: 600
cd_break: 600
# 操作随机值上限
max_knock: 3000
max_random: 2000
max_money: 700
# 操作随机值下限
min_knock: 1000
min_random: 1000
min_money: 300
