
# 操作冷却 (单位: 秒)
cd_knock: 420
cd_random: 500
cd_money: 600
cd_break: 600
cd_fight: 600
# 操作随机值上限
max_knock: 30000
max_random: 20000
max_money: 700
max_Leijie: 9
# 操作随机值下限
min_knock: 10000
min_random: 10000
min_money: 300
min_Leijie: 7